// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

function make(children) {
  return ReasonReact.wrapJsForReason(React.Fragment, { }, children);
}

export {
  make ,
  
}
/* react Not a pure module */
