// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

function setSectionRef(theRef, param) {
  console.log(theRef);
  param[/* state */1][/* childRef */1][0] = (theRef == null) ? /* None */0 : [theRef];
  return /* () */0;
}

var component = ReasonReact.reducerComponent("ReactPerimeter");

function make(onBreach, onLeave, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var handleMouseMove = function ($$event, param) {
                var state = param[/* state */1];
                var clientX = $$event.clientX;
                var clientY = $$event.clientY;
                var offsetY = window.pageYOffset;
                if (clientX > state[/* bounds */2].left && clientX < state[/* bounds */2].right && clientY > (state[/* bounds */2].top - offsetY | 0) && clientY < (state[/* bounds */2].bottom - offsetY | 0)) {
                  if (state[/* isBreached */0] === false) {
                    return Curry._1(onBreach, /* () */0);
                  } else {
                    return 0;
                  }
                } else if (state[/* isBreached */0] === true) {
                  return Curry._1(onLeave, /* () */0);
                } else {
                  return 0;
                }
              };
              var match = self[/* state */1][/* childRef */1][0];
              if (match) {
                var r = match[0];
                console.log(r);
                Curry._1(self[/* send */3], /* SetBounds */[r.getBoundingClientRect()]);
              }
              window.addEventListener("mousemove", Curry._1(self[/* handle */0], handleMouseMove));
              return /* () */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return Curry._1(children, Curry._1(self[/* handle */0], setSectionRef));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* isBreached */false,
                      /* childRef */[/* None */0],
                      /* bounds */{
                        top: 0,
                        right: 0,
                        bottom: 0,
                        left: 0
                      }
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                if (action !== 0) {
                  return /* Update */Block.__(0, [/* record */[
                              /* isBreached */false,
                              /* childRef */state[/* childRef */1],
                              /* bounds */state[/* bounds */2]
                            ]]);
                } else {
                  return /* Update */Block.__(0, [/* record */[
                              /* isBreached */true,
                              /* childRef */state[/* childRef */1],
                              /* bounds */state[/* bounds */2]
                            ]]);
                }
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* isBreached */state[/* isBreached */0],
                            /* childRef */state[/* childRef */1],
                            /* bounds */action[0]
                          ]]);
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  setSectionRef ,
  component ,
  make ,
  
}
/* component Not a pure module */
