// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as ReactPerimeter from "react-perimeter";

function make(padding, onBreach, onLeave, children) {
  return ReasonReact.wrapJsForReason(ReactPerimeter.default, {
              padding: padding,
              onBreach: onBreach,
              onLeave: onLeave
            }, children);
}

export {
  make ,
  
}
/* ReasonReact Not a pure module */
